sudo: false
language: python
cache: pip
python:
- 3.6
script:
- pipenv install
- ./create_deployment_pkg
deploy:
- provider: lambda
  function_name: uno-usage-scraper
  description: Retrieves and stores hourly usage data for an uno
    Communications Ltd. account.
  region: eu-west-1
  role: arn:aws:iam::158438328645:role/uno-usage-scraper-role
  runtime: python3.6
  module_name: main
  handler_name: lambda_handler
  zip: "/dev/shm/deploy.zip"
  timeout: 10
  memory_size: 128
  on:
    branch: latest
- provider: lambda
  function_name: uno-usage-scraper
  description: Retrieves and stores hourly usage data for an uno
    Communications Ltd. account.
  region: eu-west-1
  role: arn:aws:iam::158438328645:role/uno-usage-scraper-role
  runtime: python3.6
  module_name: main
  handler_name: lambda_handler
  zip: "/dev/shm/deploy.zip"
  timeout: 10
  memory_size: 128
  publish: true
  on:
    tags: true
- provider: releases
  file: "/dev/shm/deploy.zip"
  skip_cleanup: true
  api_key:
    secure: AcTXAJZavsjYzkYAu6GuMOTGPI9HreLCmnAAlrvK7Lbc0DpdR/4mmpwqhuZKHRL3f2MKpdD/nl60fytsLg43IlJo37baf8UK6MJIeYPczBlV3O/Uj+Tt+XWi0vZntuhTzw5e0hB8BsRYJY4e2hgZpO+0WIFIp1tubDZr9QEkYUCU0l+PoInId9G+CxAs/fLte3Ns2OW6lNMn8n/6vpihYFtIh8DaHpcKawoVXGeLE9/+iPktpw9EeGoy3R+gTB+a2PzKNkyivx3D4+Gat3e2aXFN0WnOqIEio4N47yTruEJmgKHxo31Trs1HsKO6zQbtASTqe0uC1VRcFZOpn8RWKpHIh2T5iD/Tv9f5myYPuwYHdH7a+nfRLQqacEaICv2xgRQR+evKq02sXa+ETTWpUmE3PWFK63WydsEqEbZlc91oOheTmdD/hnfUR6XKT3eqFA1ZAhlmDgGvAwx7vSYV1PE35Bb0n5EoofjjpH+DfISQrKcCNyZlZSOc+wbOL0n5Uejd1xspLN1YkWeYqipo+ggV8hm/tum8r5ttD63Pfe5/DelrJGLzMGUPzCPqDPuw0E77TrbPmzLTgPdk3XqHX8fhvaQZFYfiqYZ/ZPM/kL4AtlCuWWu6ZL9pkmsjthOkbr9d9TaFr4d3lNTfayLoe9sXEd3zxM7lpqpo6Q5XLo8=
  on:
    repo: gebn/uno-usage-scraper
    tags: true
